import type { ActionItem, ArtistRecommendation, IntelItem } from "../_types";

export const artistRecommendations: ArtistRecommendation[] = [
  {
    id: "felix-riano-the-chase",
    artist: "Felix Riaño",
    workTitle: "The Chase · 历史与未来的碰撞",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/5DTFkHkJUwSsabYs6hHcES.jpg",
    sourceUrl: "https://www.creativebloq.com/3d/3d-art/this-game-concept-artist-explores-fantastical-ideas-in-historical-settings",
    sourceLabel: "CREATIVE BLOQ · ARTIST FEATURE",
    style: "半写实",
    worldView: "荒野西部仍保留马匹、尘土与拓荒者秩序，但巨型飞船已经成为可被追逐与劫掠的日常科技。历史语境与未来设备的冲突，让世界观在一张图里成立。",
    artDirection: "硬表面科幻 × 历史荒野",
    studyFocus: "学习如何用一个高反差的时代错位，快速建立叙事钩子与尺度感。",
    featured: true,
  },
  {
    id: "tarmo-juhola-brutalist-fantasy",
    artist: "Tarmo Juhola",
    workTitle: "Brutalist Fantasy · 悬崖般的建筑",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/zibyA3pak49AjsPWUCDbkZ.jpg",
    sourceUrl: "https://www.creativebloq.com/3d/3d-art/turning-architecture-skills-into-epic-brutalist-fantasy-art",
    sourceLabel: "CREATIVE BLOQ · ARTIST FEATURE",
    style: "写实",
    worldView: "巨构建筑不再只是背景，而是像山体一样压迫角色的文明遗迹。粗野主义轮廓与奇幻尺度结合，暗示一个崇拜力量、秩序和永恒材料的古老社会。",
    artDirection: "粗野主义 × 史诗奇幻",
    studyFocus: "观察大轮廓、重复模块和人物尺度如何共同制造庄严感。",
  },
  {
    id: "choomcherd-virapat-phaya-akat",
    artist: "Choomcherd Virapat",
    workTitle: "Phaya Akat · 天空战士",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/tciejDt5qNcEuMyr3FrtmB.jpg",
    sourceUrl: "https://www.creativebloq.com/art/digital-art/this-artists-created-a-fantasy-world-inspired-by-traditional-thai-culture",
    sourceLabel: "CREATIVE BLOQ · IMAGINEFX",
    style: "风格化",
    worldView: "以泰国文化与建筑为根基的中世纪幻想世界。温泉村落、地下宫殿与飞行战船共享同一套文化母题，让生活空间、仪式和战争机器彼此关联。",
    artDirection: "泰式文化母题 × 中世纪幻想",
    studyFocus: "学习从真实地域文化提炼形制，而不是只在表面堆叠装饰符号。",
  },
];

export const intelItems: IntelItem[] = [
  {
    id: "scenario-style",
    title: "用风格模型锁定俯视角手游场景的视觉语言",
    summary: "从少量自有参考建立一致的配色、笔触与轮廓规则，适合验证风格化场景的批量概念探索。",
    source: "SCENARIO · OFFICIAL",
    publishedAt: "2 小时前",
    url: "https://help.scenario.com/articles/8374017641-train-a-style-model",
    style: "风格化",
    direction: "美术方向",
    type: "制作案例",
    value: "立即尝试",
    signal: "与你的目标高度相关",
    featured: true,
  },
  {
    id: "marble-world",
    title: "Marble 世界生成：从粗模到可导出的场景网格",
    summary: "持续性 3D 世界、碰撞网格与 DCC 导出正在靠近真实制作流程，当前更适合前期空间原型。",
    source: "WORLD LABS · DOCS",
    publishedAt: "今天",
    url: "https://docs.worldlabs.ai/marble/export/mesh",
    style: "写实",
    direction: "开发技术",
    type: "AI 工具",
    value: "值得关注",
    signal: "前沿度 92",
  },
  {
    id: "hunyuan-pbr",
    title: "Hunyuan3D 2.1 的 PBR 材质输出是否能进入 UE5？",
    summary: "开源图生 3D 流程已经覆盖几何和 PBR 纹理，真正值得测试的是轮廓保持、拓扑清理和修模时间。",
    source: "TENCENT HUNYUAN · GITHUB",
    publishedAt: "昨天",
    url: "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1",
    style: "半写实",
    direction: "混合方向",
    type: "前沿研究",
    value: "立即尝试",
    signal: "可形成作品集过程图",
  },
  {
    id: "ue-pcg",
    title: "UE5 PCG 分层生成：风格化森林的可控散布方法",
    summary: "用大网格控制树木和岩石、小网格补充花草细节，重点展示规则设计、可控随机与性能意识。",
    source: "UNREAL ENGINE · DOCS",
    publishedAt: "2 天前",
    url: "https://dev.epicgames.com/documentation/unreal-engine/using-pcg-generation-modes-in-unreal-engine",
    style: "风格化",
    direction: "开发技术",
    type: "制作案例",
    value: "立即尝试",
    signal: "匹配 UE5 场景岗位",
  },
  {
    id: "substance-texture",
    title: "Substance 3D 的生成式纹理如何保留手绘感",
    summary: "Text-to-Texture 与 Image-to-Material 可用于前期变体探索，但需要人工统一粗糙度、尺度和色彩节奏。",
    source: "ADOBE · RELEASE NOTES",
    publishedAt: "3 天前",
    url: "https://experienceleague.adobe.com/en/docs/substance-3d-sampler/using/features-and-workflows/generative-workflows",
    style: "风格化",
    direction: "美术方向",
    type: "AI 工具",
    value: "值得关注",
    signal: "材质方向",
  },
  {
    id: "genie-world",
    title: "实时世界模型距离游戏生产还有多远？",
    summary: "交互世界生成展示了快速原型的潜力，但缺少稳定资产、可编辑拓扑和确定性，暂不替代场景生产。",
    source: "DEEPMIND · RESEARCH",
    publishedAt: "本周",
    url: "https://deepmind.google/models/genie/",
    style: "写实",
    direction: "开发技术",
    type: "前沿研究",
    value: "仅作参考",
    signal: "长期观察",
  },
];

export const starterActions: ActionItem[] = [
  {
    id: "action-1",
    title: "测试一张风格化小屋概念图到 3D 的轮廓保持",
    output: "生成结果、人工修正前后对比、3 条结论",
    duration: "2 小时",
    skill: "AIGC 实验 / 造型判断",
    done: false,
  },
  {
    id: "action-2",
    title: "拆解一张俯视角场景的色彩层级",
    output: "5 色主色板与小屏可读性标注",
    duration: "30 分钟",
    skill: "构图 / 色彩 / 手游适配",
    done: false,
  },
  {
    id: "action-3",
    title: "整理 UE5 场景模块化规范页",
    output: "网格、命名、贴图与引擎截图一页",
    duration: "1 天",
    skill: "生产流程 / 引擎落地",
    done: true,
  },
];
