import type { ActionItem, IntelItem } from "../_types";

export const intelItems: IntelItem[] = [
  {
    id: "scenario-style",
    title: "用风格模型锁定俯视角手游场景的视觉语言",
    summary: "从少量自有参考建立一致的配色、笔触与轮廓规则，适合验证风格化场景的批量概念探索。",
    source: "SCENARIO · OFFICIAL",
    publishedAt: "2 小时前",
    url: "https://help.scenario.com/articles/8374017641-train-a-style-model",
    style: "风格化",
    direction: "美术方向",
    type: "制作案例",
    value: "立即尝试",
    signal: "与你的目标高度相关",
    featured: true,
  },
  {
    id: "marble-world",
    title: "Marble 世界生成：从粗模到可导出的场景网格",
    summary: "持续性 3D 世界、碰撞网格与 DCC 导出正在靠近真实制作流程，当前更适合前期空间原型。",
    source: "WORLD LABS · DOCS",
    publishedAt: "今天",
    url: "https://docs.worldlabs.ai/marble/export/mesh",
    style: "写实",
    direction: "开发技术",
    type: "AI 工具",
    value: "值得关注",
    signal: "前沿度 92",
  },
  {
    id: "hunyuan-pbr",
    title: "Hunyuan3D 2.1 的 PBR 材质输出是否能进入 UE5？",
    summary: "开源图生 3D 流程已经覆盖几何和 PBR 纹理，真正值得测试的是轮廓保持、拓扑清理和修模时间。",
    source: "TENCENT HUNYUAN · GITHUB",
    publishedAt: "昨天",
    url: "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1",
    style: "半写实",
    direction: "混合方向",
    type: "前沿研究",
    value: "立即尝试",
    signal: "可形成作品集过程图",
  },
  {
    id: "ue-pcg",
    title: "UE5 PCG 分层生成：风格化森林的可控散布方法",
    summary: "用大网格控制树木和岩石、小网格补充花草细节，重点展示规则设计、可控随机与性能意识。",
    source: "UNREAL ENGINE · DOCS",
    publishedAt: "2 天前",
    url: "https://dev.epicgames.com/documentation/unreal-engine/using-pcg-generation-modes-in-unreal-engine",
    style: "风格化",
    direction: "开发技术",
    type: "制作案例",
    value: "立即尝试",
    signal: "匹配 UE5 场景岗位",
  },
  {
    id: "substance-texture",
    title: "Substance 3D 的生成式纹理如何保留手绘感",
    summary: "Text-to-Texture 与 Image-to-Material 可用于前期变体探索，但需要人工统一粗糙度、尺度和色彩节奏。",
    source: "ADOBE · RELEASE NOTES",
    publishedAt: "3 天前",
    url: "https://experienceleague.adobe.com/en/docs/substance-3d-sampler/using/features-and-workflows/generative-workflows",
    style: "风格化",
    direction: "美术方向",
    type: "AI 工具",
    value: "值得关注",
    signal: "材质方向",
  },
  {
    id: "genie-world",
    title: "实时世界模型距离游戏生产还有多远？",
    summary: "交互世界生成展示了快速原型的潜力，但缺少稳定资产、可编辑拓扑和确定性，暂不替代场景生产。",
    source: "DEEPMIND · RESEARCH",
    publishedAt: "本周",
    url: "https://deepmind.google/models/genie/",
    style: "写实",
    direction: "开发技术",
    type: "前沿研究",
    value: "仅作参考",
    signal: "长期观察",
  },
];

export const starterActions: ActionItem[] = [
  {
    id: "action-1",
    title: "测试一张风格化小屋概念图到 3D 的轮廓保持",
    output: "生成结果、人工修正前后对比、3 条结论",
    duration: "2 小时",
    skill: "AIGC 实验 / 造型判断",
    done: false,
  },
  {
    id: "action-2",
    title: "拆解一张俯视角场景的色彩层级",
    output: "5 色主色板与小屏可读性标注",
    duration: "30 分钟",
    skill: "构图 / 色彩 / 手游适配",
    done: false,
  },
  {
    id: "action-3",
    title: "整理 UE5 场景模块化规范页",
    output: "网格、命名、贴图与引擎截图一页",
    duration: "1 天",
    skill: "生产流程 / 引擎落地",
    done: true,
  },
];

